engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.codeclimate.json
    checks:
      max-classes-per-file:
        enabled: false
      no-inferrable-types:
        enabled: false
ratings:
  paths:
    - "**.ts"
exclude_paths:
  - bin
  - node_modules
  - typings
  - coverage
  - dist